### PR TITLE
Prepare for rollout of "Key Takeaways" and "Q and A Explainer" articles

### PR DESCRIPTION
**Pull request by simonbyford**
## What does this change?

In preparation for roll out...

- removes feature switches
- updates icons
- renames "Q and A" to "Q and A Explainer"

Similar to this composer PR: https://github.com/guardian/flexible-content/pull/4744

## How to test

Run locally or deploy to CODE. Hit `shift-f12`. Ensure the switches for "Key Takeaways" and "Q and A Explainer" have gone. Look in the "Create new" menu. Can you create "Key Takeaways" and "Q and A Explainer" articles?

## Images

Screenshot 2024-04-30 at 16 52 12

Screenshot 2024-04-30 at 16 58 22

### CODE REVIEW

**Comment by simonbyford** [comment]
Unfortunately my feature switches menu (`shift-f12`) now looks like this:

Screenshot 2024-04-30 at 16 54 21

I'm guessing I still have records stored somewhere which need to be removed?

How are feature switch records persisted?

**Comment by rhystmills** [comment]
> Unfortunately my feature switches menu (`shift-f12`) now looks like this:
> 
> Screenshot 2024-04-30 at 16 54 21
> 
> I'm guessing I still have records stored somewhere which need to be removed?
> 
> How are feature switch records persisted?

Looks like an existing bug to me, I'll take a look this morning. The values are persisted in DynamoDB, as part of preferences, I think.

**Comment by rhystmills** [comment]
> > Unfortunately my feature switches menu (`shift-f12`) now looks like this:
> > Screenshot 2024-04-30 at 16 54 21
> > I'm guessing I still have records stored somewhere which need to be removed?
> > How are feature switch records persisted?
> 
> Looks like an existing bug to me, I'll take a look this morning. The values are persisted in DynamoDB, as part of preferences, I think.

I've pushed a fix for that bug.

**Review by rhystmills — APPROVED** [review]
Working nicely - can see the content types in the dropdown and able to create them successfully.

**Pull request merged**
