### PR TITLE
updates vulnerable dependancies via snyk

### PR DESCRIPTION
**Pull request by dskamiotis**
## What does this change?

This addresses vulnerabilities presented in Snyk:
image

## Libraries updated
Some key libraries were updated:
- angular
- lodash
- ua-parser-js
- jquery-ui

## How to test

Deploy to CODE and check https://workflow.code.dev-gutools.co.uk/dashboard to ensure functioning as expected.
This also be done as instructed [here](https://workflow.code.dev-gutools.co.uk/dashboard)

Run tests within `sbt test` 

Deploy branch to CODE tested in `https://workflow.code.dev-gutools.co.uk/dashboard`
- Created new article successfully
- Modified writers status
image

## How can we measure success?

We can see the number and level of vulnerabilies in [Snyk](https://app.snyk.io/org/guardian/project/581b49a4-bdbb-4d3f-899f-b7521c73ce24)

Check vulnerabilities after updates using Snyk CLI command `snyk test --all-projects`:
Before updates:
image
After updates:
image

That workflow-frontend is working as expected https://workflow.code.dev-gutools.co.uk/dashboard
## Have we considered potential risks?

Risks pertaining to the updates causing a breaking change are mitigated through thorough testing, see above.

### CODE REVIEW

**Comment by twrichards** [comment]
unfortunately `workflow-frontend` `CODE` isn't working with this deployed

**Comment by dskamiotis** [comment]
> unfortunately `workflow-frontend` `CODE` isn't working with this deployed

thanks @twrichards apologies if that caused anyone problems, Ive re-deployed main to code, I believe some of the updates were breaking changes so, am tempted to do those again. I may just rebase off main for this branch ad re do to the updates in a more incremental fashion?

**Comment by SHession** [comment]
I had a bit of trouble with this locally and on CODE so I updated some of the other Angular dependencies and it seems to have improved it. Worth testing some more to be confident it works.

**Comment by dskamiotis** [comment]
Thanks @SHession, for some reason it was ok when I deployed and was rendering well. 
This update seems to work fine now 👍 
Tested and deployed in CODE

**Review by SHession — APPROVED** [review]
Tested some key workflows on CODE. Workflow behaved as expected.

I did uncover one issue which appears on main. If you try to change the `Publication date` of a stub it doesn't work. It seems to send a PUT request with an empty payload: 
image

Worth investigating separately but non-blocking for this work.

**Comment by dskamiotis** [comment]
Thanks @SHession we can create a ticket in the backlog for this

**Pull request merged**
