### PR TITLE
Enables cross domain HTTP DELETE requests (for Composer)

### PR DESCRIPTION
**Pull request by shtukas**
This change allows a new feature being developed in Composer
to send HTTP DELETE requests to workflow-frontend.

### CODE REVIEW

**Comment by philmcmahon** [comment]
This looks good. Worth testing on CODE first.

**Comment by shtukas** [comment]
Deployed to CODE (build 27; https://riffraff.gutools.co.uk/deployment/view/ac9b5e5a-a6e5-41ee-986c-f3c7c0584a40 ) and ran workflow-integration-tests ( https://circleci.com/gh/guardian/workflow-integration-tests/113 )

**Comment by philmcmahon** [comment]
👍

**Comment by shtukas** [comment]
Also manually checked on CODE (created an article and deleted it).

**Pull request merged**
